CREATE TABLE CLIENTE(
    ID_CLIENTE NUMERIC(4) NOT NULL ,
    TIPO_DOCUMENTO VARCHAR2(240) NOT NULL,
    DOCUMENTO CHAR(11) NOT NULL UNIQUE,
    NOMBRES VARCHAR2(240) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(240) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(240) NOT NULL,
    DOMICILIO VARCHAR2(240) NOT NULL,
    TELEFONO CHAR(9) NOT NULL,
    EMAIL VARCHAR2(240) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE RECLAMO(
    ID_RECLAMO NUMERIC(4) NOT NULL,
    DESCRIPCION VARCHAR2(2000) NOT NULL,
    ESTADO VARCHAR2(25) DEFAULT 'En Pendiente' NOT NULL,
    ID_CLIENTE NUMERIC(4) NOT NULL,
    CONSTRAINT PK_RECLAMO PRIMARY KEY(ID_RECLAMO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

--CREATE SEQUENCE SEQ_CLIENTE;
--CREATE SEQUENCE SEQ_RECLAMO;

--INSERT INTOS DE CLIENTES
INSERT INTO CLIENTE(ID_CLIENTE,TIPO_DOCUMENTO,DOCUMENTO,NOMBRES,APELLIDO_PATERNO,APELLIDO_MATERNO,DOMICILIO,TELEFONO,EMAIL)
VALUES(SEQ_CLIENTE.NEXTVAL,'DNI','73674986','Paolo','Pisfil','Castro','jr. Cabana 283','966016032','paolopc54@gmail.com');

INSERT INTO CLIENTE(ID_CLIENTE,TIPO_DOCUMENTO,DOCUMENTO,NOMBRES,APELLIDO_PATERNO,APELLIDO_MATERNO,DOMICILIO,TELEFONO,EMAIL)
VALUES(SEQ_CLIENTE.NEXTVAL,'DNI','73528366','Yajaira','Burga','Ortiz','Santa Maria II','964601973','yajairasbo93@gmail.com');


--INSERT INTOS DE RECLAMOS
INSERT INTO RECLAMO(ID_RECLAMO,DESCRIPCION,ID_CLIENTE)
VALUES (SEQ_RECLAMO.NEXTVAL,'PRUEBA',1);

INSERT INTO RECLAMO(ID_RECLAMO,DESCRIPCION,ID_CLIENTE)
VALUES (SEQ_RECLAMO.NEXTVAL,'PRUEBA2',1);

INSERT INTO RECLAMO(ID_RECLAMO,DESCRIPCION,ID_CLIENTE)
VALUES (SEQ_RECLAMO.NEXTVAL,'PRUEBA3',2);

INSERT INTO RECLAMO(ID_RECLAMO,DESCRIPCION,ID_CLIENTE)
VALUES (SEQ_RECLAMO.NEXTVAL,'PRUEBA4',2);

INSERT INTO RECLAMO(ID_RECLAMO,DESCRIPCION,ID_CLIENTE)
VALUES (SEQ_RECLAMO.NEXTVAL,'PRUEBA5',2);

CREATE VIEW V_RECLAMO_CLIENTE
AS
    SELECT    
        R.ID_RECLAMO,
        R.DESCRIPCION,
        R.ESTADO,
        C.ID_CLIENTE,
        C.TIPO_DOCUMENTO,
        C.DOCUMENTO,
        C.NOMBRES,
        C.APELLIDO_PATERNO,
        C.APELLIDO_MATERNO,
        C.DOMICILIO,
        C.TELEFONO,
        C.EMAIL
    FROM 
        RECLAMO R INNER JOIN CLIENTE C
        ON R.ID_CLIENTE = C.ID_CLIENTE;
